In [42]:
# !pip install scikit-learn==0.22

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.ensemble import  VotingClassifier
%matplotlib inline

In [3]:
# Question # 1
dataset = pd.read_csv("dataset.csv")

In [4]:
dataset

Student_ID  Marks  Attend  Subjects Grades
0     p181234      1       1         1      S
1     p180001      1       1         0      S
2     p180002      0       1         1      U
3     p180003      1       0         0      S
4     p180004      0       1         1      U
5     p180005      1       0         1      S
6     p180006      1       1         1      S
7     p180007      0       0         0      U
8     p180007      0       0         1      U
9     p180008      1       1         1      U
10    p180009      0       1         1      S
11    p180010      1       0         0      S
12    p180011      0       1         1      S

In [6]:
X = dataset[["Marks","Attend","Subjects"]]


In [7]:
Y = dataset["Grades"]
Y

0     S
1     S
2     U
3     S
4     U
5     S
6     S
7     U
8     U
9     U
10    S
11    S
12    S
Name: Grades, dtype: object

In [8]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.4,random_state=22)

In [9]:
svm1 = svm.SVC(kernel='linear',C=0.1,probability=True).fit(X_train, Y_train)

In [10]:
svm1_pred = svm1.predict(X_test)
svm1_pred

array(['S', 'S', 'S', 'S', 'S', 'S'], dtype=object)

In [11]:
svm2 = svm.SVC(kernel='linear',C=0.2,probability=True).fit(X_train, Y_train)

In [12]:
svm2_pred = svm2.predict(X_test)
svm2_pred

array(['S', 'S', 'S', 'S', 'S', 'S'], dtype=object)

In [13]:
svm3 = svm.SVC(kernel='linear',C=0.3,probability=True).fit(X_train, Y_train)

In [14]:
svm3_pred = svm3.predict(X_test)
svm3_pred

array(['S', 'S', 'S', 'S', 'S', 'S'], dtype=object)

In [15]:
svm4 = svm.SVC(kernel='linear',C=0.4,probability=True).fit(X_train, Y_train)
svm4_pred = svm4.predict(X_test)
svm4_pred

array(['S', 'S', 'S', 'S', 'S', 'S'], dtype=object)

In [16]:
svm5 = svm.SVC(kernel='linear',C=0.5,probability=True).fit(X_train, Y_train)
svm5_pred = svm5.predict(X_test)
svm5_pred

array(['U', 'S', 'U', 'U', 'U', 'S'], dtype=object)

In [17]:
svm6 = svm.SVC(kernel='linear',C=0.6,probability=True).fit(X_train, Y_train)
svm6_pred = svm6.predict(X_test)
svm6_pred

array(['U', 'S', 'U', 'U', 'U', 'S'], dtype=object)

In [18]:
svm7 = svm.SVC(kernel='linear',C=0.7,probability=True).fit(X_train, Y_train)
svm7_pred = svm7.predict(X_test)
svm7_pred

array(['U', 'S', 'U', 'U', 'U', 'S'], dtype=object)

In [19]:
svm8 = svm.SVC(kernel='linear',C=0.8,probability=True).fit(X_train, Y_train)
svm8_pred = svm8.predict(X_test)
svm8_pred

array(['U', 'S', 'U', 'U', 'U', 'S'], dtype=object)

In [20]:
svm9 = svm.SVC(kernel='linear',C=0.9,probability=True).fit(X_train, Y_train)
svm9_pred = svm9.predict(X_test)
svm9_pred

array(['U', 'S', 'U', 'U', 'U', 'S'], dtype=object)

In [21]:
svm10 = svm.SVC(kernel='linear',C=1.0,probability=True).fit(X_train, Y_train)
svm10_pred = svm10.predict(X_test)
svm10_pred

array(['U', 'S', 'U', 'U', 'U', 'S'], dtype=object)

In [22]:
hard_voting = VotingClassifier(estimators=[('svm1', svm1), ('svm2', svm2), ('svm3', svm3),('svm4',svm4),('svm5',svm5),('svm6',svm6),('svm7',svm7),('svm8',svm8),('svm9',svm9),('svm10',svm10)], voting='hard')
hard_voting.fit(X_train,Y_train)
hard_voting.predict(X_test)

array(['U', 'S', 'U', 'U', 'U', 'S'], dtype=object)

In [23]:
weighted_voting = VotingClassifier(estimators=[('svm1', svm1), ('svm2', svm2), ('svm3', svm3),('svm4',svm4),('svm5',svm5),('svm6',svm6),('svm7',svm7),('svm8',svm8),('svm9',svm9),('svm10',svm10)], voting='soft',weights=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0])
weighted_voting.fit(X_train,Y_train)
weighted_voting.predict(X_test)

array(['U', 'S', 'U', 'U', 'U', 'S'], dtype=object)

In [40]:
# Question # 2
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.metrics import jaccard_similarity_score

In [33]:
decision_tree = DecisionTreeClassifier(random_state=0, max_depth=3)
decision_tree.fit(X_train,Y_train)
dt_pred = decision_tree.predict(X_test)

In [34]:
print(classification_report(Y_test, dt_pred))

              precision    recall  f1-score   support

           S       0.50      0.33      0.40         3
           U       0.50      0.67      0.57         3

    accuracy                           0.50         6
   macro avg       0.50      0.50      0.49         6
weighted avg       0.50      0.50      0.49         6



In [41]:
 jaccard_similarity_score(Y_test, dt_pred, normalize=False)

In [36]:
# Question # 3
from sklearn.cluster import KMeans


In [37]:
kmeans = KMeans(n_clusters=3,init = 'k-means++',   max_iter = 100, n_init = 10, random_state = 0) #Applying Kmeans classifier


In [38]:
kmeans.fit(X_train)

KMeans(max_iter=100, n_clusters=3, random_state=0)

In [39]:
print(kmeans.cluster_centers_) #display cluster centers
labels = kmeans.labels_
labels


[[1.00000000e+00 5.55111512e-17 3.33333333e-01]
 [0.00000000e+00 5.00000000e-01 1.00000000e+00]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00]]


array([0, 1, 2, 0, 2, 1, 0], dtype=int32)